### ISSUE TITLE
Настройка переключений в HA

### ISSUE THREAD

**Issue by DimsterTim** [Whilser/GyverLamp#4]
Поделитесь пожалуйста настройкой автоматизаций в Home Assistant для переключения эффектов. 

Заметил, что лампа подвисает на несколько секунд - приостанавливается анимация лампы при обновлении веб страницы. Это неизбежно?

**Comment by Whilser** [comment]
Вообще, не должно ничего подвисать при обновлении веб страницы. Покажи лог из консоли лампы во время обновления веб страницы. 

Пример автоматизации в ХА:

```

- alias: Gyver Lamp Effect
  trigger:

  action:
    - service: light.turn_on
      entity_id: light.gyver_lamp
      data:
        effect: Конфетти      
```
